# Generated by Django 5.2.4 on 2025-07-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
